version: '3.8'

services:
  pcs-tracker:
    build: 
      context: .
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
    image: tebwritescode/pocket-change-showdown:latest
    container_name: pcs-tracker
    ports:
      - "5001:5001"
    volumes:
      - pcs-data:/app/data
      - pcs-uploads:/app/uploads
    environment:
      - SECRET_KEY=${SECRET_KEY:-pcs-secret-key-2024}
      - FLASK_ENV=${FLASK_ENV:-production}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  pcs-data:
    driver: local
  pcs-uploads:
    driver: local