apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pcs-data-pvc
  namespace: pcs-tracker
  labels:
    app: pcs-tracker
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pcs-uploads-pvc
  namespace: pcs-tracker
  labels:
    app: pcs-tracker
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi